### ISSUE TITLE
Plugin does not install properly

### ISSUE THREAD

**Issue by agnivade** [yields/sublime-go#27]
I am trying to follow the instructions and install the package. But somehow I am unable to make it work.

I added the repo.json link and installed the package.

But after that, I don't see an entry under the "Package Settings" dropdown, and neither do I see a directory under `~/.config/sublime-text-3/Packages`.

When I try to open the config file (Go: open config), I see this error in the console:

`error: The settings file "res://Packages/Golang/Golang.sublime-settings" could not be opened`

Let me know how can I provide more information.

**Comment by yields** [comment]
Ah, it got added to package control, so just search `Golang` and install.

**Comment by agnivade** [comment]
Sorry, it still doesn't work. Nothing happens, there is no code highlighting.

**Comment by yields** [comment]
hmm, that's very odd, this plugin doesn't contain any code highlighting as it comes with ST3 by default.

Can you try and see if the plugin is actually installed by printing `Golang` from the ST3 console?

**Comment by agnivade** [comment]
Sorry for the delay. I haven't had the time to look into this. I will try to take a look this weekend.

**Comment by agnivade** [comment]
Ok, I can see the plugin getting installed. But I see these errors in the console.

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 701, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/listeners.py", line 30, in on_query_completions
    return gocode.complete(self.view, points[0])
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/decorators.py", line 12, in tracer
    resp = func(*args, **kwargs)
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/gocode.py", line 21, in complete
    res = cmd.run()
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/exec.py", line 36, in run
    env = goenv(self.cwd)
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/decorators.py", line 34, in call
    mem[args] = func(*args, **kwargs)
  File "/home/agniva/.config/sublime-text-3/Installed Packages/Golang.sublime-package/go/exec.py", line 72, in goenv
    proc = Popen(["go", "env"], stdout=PIPE, cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'go'
```

`go` is in my $PATH. So I am not sure what the problem is.

**Comment by yields** [comment]
My guess is that sublime doesn't pick up your `$PATH` for some reason, you can confirm by doing the following:

1. In your terminal (where `go(1)` is available), run `$ echo $PATH`
2. In sublime, open the console and run: `import os; os.environ['PATH']`

**Comment by yields** [comment]
Feel free to re-open if the settings fix doesn't work for you.

**Comment by agnivade** [comment]
Thanks for the follow up. Appreciate it.
