### ISSUE TITLE
go vet failing on fresh install

### ISSUE THREAD

**Issue by mcscope** [yields/sublime-go#31]
I'm setting up my golang environment for the first time and I installed this package and it's dependencies as one of the first moves. 
I'm seeing an error on the console when I run go vet on a helloworld program. Here's the error
```Traceback (most recent call last):
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/decorators.py", line 51, in <lambda>
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/decorators.py", line 57, in call
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/decorators.py", line 12, in tracer
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/vet.py", line 37, in run
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/lint.py", line 42, in parse
  File "/Users/ladyred/Library/Application Support/Sublime Text 3/Installed Packages/Golang.sublime-package/go/lint.py", line 136, in parse
ValueError: invalid literal for int() with base 10: 'package ./golang.org/x/lint'```

When run in terminal:

```
[ladyred@crimson: ~/code/go/src>] go vet hello_world.go 
# command-line-arguments
./hello_world.go:19:2: Printf format %/ has unknown verb /
```

I'm trying to figure out the exact command being run by the plugin since it's clearly getting a string where it expects some kinda status code.

**Comment by mcscope** [comment]
So I think I discovered the answer - All the go code needs to be in its own folder. Once I moved my hello world into a hello/hello_world.go subfolder then go vet, go test, etc started to work.

**Comment by piotrkubisa** [comment]
Hmm, I would say it is a place for a fix. How exactly your workspace looked?

**Comment by yields** [comment]
Agreed this should be fixed, the plugin should work on one-off files too.
